/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The parsed document — equivalent of `document` in the browser. */
export declare class JsDocument {
  /** Parse an HTML-like string and return a JsDocument. */
  static parse(html: string): JsDocument
  /** The document root (nodeType 9). */
  get documentElement(): JsElement
  querySelector(selector: string): JsElement | null
  querySelectorAll(selector: string): Array<JsElement>
  /** Serialise the entire document back to a string. */
  serialize(): string
}

/** A handle to a single DOM node (element, text, or document root). */
export declare class JsElement {
  /** Lowercase tag name, or null for text/document nodes. */
  get tagName(): string | null
  /** 1 = Element, 3 = Text, 9 = Document */
  get nodeType(): number
  get textContent(): string
  getInnerHtml(): string
  setInnerHtml(html: string): void
  get outerHtml(): string
  getAttribute(name: string): string | null
  /** Returns true even for boolean attributes that have no value. */
  hasAttribute(name: string): boolean
  /** Pass `null` as value to set a boolean attribute with no value. */
  setAttribute(name: string, value?: string | undefined | null): void
  removeAttribute(name: string): void
  children(): Array<JsElement>
  get parent(): JsElement | null
  querySelector(selector: string): JsElement | null
  querySelectorAll(selector: string): Array<JsElement>
}
